### ISSUE TITLE
Question: How you get time and key?

### ISSUE THREAD

**Issue by emdy** [DoctorMcKay/steam-twofactor-server#3]
What cind of stuff u use to get time and key? Where i can read about it or test it?

**Comment by DoctorMcKay** [comment]
I don't understand the question.

**Comment by emdy** [comment]
@DoctorMcKay i meen https://github.com/DoctorMcKay/node-steam-totp/blob/master/index.js#L53 how you get KEY. i know time is current time.
Iam tried do with php hash_hmac("sha1", $identitySecret, true) to compile identitySecret. 
But how i can use writeUInt32BE with php to get a key?

**Comment by DoctorMcKay** [comment]
How on earth did you end up here?

**Comment by emdy** [comment]
@DoctorMcKay Sir, how i can get(generate) key with php? I know my identy secret code.

**Comment by DoctorMcKay** [comment]
You're in the very wrong place to be asking this.

You might get some help at https://dev.doctormckay.com
